name: Issue handling

on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Automatically close issues that don't follow the issue template
        uses: lucasbento/auto-close-issues@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          closed-issues-label: "🙁 Not following issue template"
  add_label_rn_version:
    runs-on: ubuntu-latest
    needs: auto_close_issues
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add label with the React Native version
        uses: ./actions/addLabelRNVersion
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
