name: Handle new release

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Handle new release
        uses: ./actions/newRelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
