name: Synchronise release versions

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  sync_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Sync releases
        uses: ./actions/syncReleases
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
